blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ï¸ Chat
    url: https://discord.com/channels/1390650823855439903/1435981804925489172
    about: Our Discord server is active and is used for real-time discussions including contribution collaboration, questions, and more!
  - name: ğŸ’¬ Discussion
    url: https://github.com/atomic-ehr/codegen/discussions/new
    about: Please create a discussion.
