blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ï¸ Chat
    url: https://discord.gg/rumCG3dwgF
    about: Our Discord server is active and is used for real-time discussions including contribution collaboration, questions, and more!
  - name: ğŸ’¬ Discussion
    url: https://github.com/atomic-ehr/codegen/discussions/new
    about: Please create a discussion
